# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EAn3CqgnraYovE5h5LJxsKKHLOqZXBE
"""

import random

# The computer chooses a number between 1 and 50
secret_number = random.randint(1, 50)

print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 50.")

attempts = 0
game_over = False

while game_over == False:

    guess = input("Enter your guess: ")

    # TODO 1: Convert guess to an integer
    guess = int(guess)

    # TODO 2: Increase attempts by 1
    attempts += 1

    # TODO 3: If guess is greater than secret_number:
    #           print "Too high!"

    # TODO 4: If guess is less than secret_number:
    #           print "Too low!"

    # TODO 5: If guess equals secret_number:
    #           print "Correct! You guessed it in X attempts."
    #           set game_over to True

    if guess > secret_number:
      print("Too high!")
    elif guess < secret_number:
      print("Too low!")
    else:
      print("Correct! You guessed it in ", attempts, " attempts.")
      game_over = True